---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  annotations:
    lbipam.cilium.io/ips: 10.20.30.209
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres17
    cnpg.io/instanceRole: primary
