---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: restore-ctrl-uptime-kuma
  namespace: uptime-kuma
spec:
  trigger:
    manual: restore-once
  restic:
    repository: uptime-kuma-restic-target
    destinationPVC: uptime-kuma-data
    copyMethod: Direct
