---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.14
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 1883
      socket:
        enabled: true
        ports:
          socket:
            enabled: true
            port: 9001
            protocol: TCP
            targetPort: 9001
    auth:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v1
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto
