---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-relay
      version: 0.2.3
      sourceRef:
        kind: HelmRepository
        name: tailscale-relay
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      authKey: "${SECRET_TAILSCALE_AUTH_KEY}"
      variables:
        TAILSCALE_ADVERTISE_ROUTES: "${TAILSCALE_ADVERTISE_ROUTES}"
        TAILSCALE_HOSTNAME: "tailscale-relay-${CLUSTER_NAME}"
