---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - config-pvc.yaml
  - media-pvc.yaml
  - helm-release.yaml
  - volsync.yaml
configMapGenerator:
  - name: frigate-config
    files:
      - config.yml=./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
