---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mainnet-geth
  namespace: blockchain
spec:
  storageClassName: ceph-block-nvme-norepl
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
