apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mev-boost
  namespace: blockchain
spec:
  replicas: 1
  serviceName: mev-boost
  selector:
    matchLabels:
      app: mev-boost
  template:
    metadata:
      labels:
        app: mev-boost
    spec:
      containers:
        - name: mev-boost
          image: flashbots/mev-boost:1.6
          ports:
            - containerPort: 18550
          args:
            - -mainnet
            - -loglevel=debug
            - -addr=0.0.0.0:18550
            - -relay-check
            - "-relays=https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-goerli.flashbots.net"
