apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: charon
  namespace: blockchain
spec:
  serviceName: "charon"
  replicas: 1
  selector:
    matchLabels:
      app: charon
  template:
    metadata:
      labels:
        app: charon
    spec:
      containers:
        - name: charon
          image: obolnetwork/charon:v0.18.0
          ports:
            - containerPort: 3610
              name: tcp
              protocol: TCP
          env:
            - name: CHARON_BEACON_NODE_ENDPOINTS
              value: http://mainnet-prysm:3500
            - name: CHARON_LOG_LEVEL
              value: info
            - name: CHARON_LOG_FORMAT
              value: console
            - name: CHARON_P2P_RELAYS
              value: https://0.relay.obol.tech
            - name: CHARON_P2P_EXTERNAL_HOSTNAME
              value: clusterfucks-leeward
            - name: CHARON_P2P_TCP_ADDRESS
              value: 0.0.0.0:3610
            - name: CHARON_VALIDATOR_API_ADDRESS
              value: 0.0.0.0:3600
            - name: CHARON_MONITORING_ADDRESS
              value: 0.0.0.0:3620
            - name: CHARON_BUILDER_API
              value: "false"
          volumeMounts:
            - name: charon-data
              mountPath: /opt/charon/.charon
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - wget -qO- http://localhost:3620/readyz
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - wget -qO- http://localhost:3620/readyz
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: charon-data
          persistentVolumeClaim:
            claimName: obol-charon
