---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediamega-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: cephfs-hdd
