# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData:
    id_rsa: ENC[AES256_GCM,data:dYtm+o8=,iv:hdjFq8PgcLYcl4lwwIAGOhZPXd8iTW3B6LGaUeqE8GQ=,tag:KMFLxo4Lz4NhrmA+K9O8Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpS0hOQlpkNGU3cW02YUMv
            K3JjNWpLKzRpNGlINGhkalBCNkd6NWk3Q1NjCmpBOEFreVpWYVBpdjAyTDcydURH
            cENCOGhwRXBCVmVtODR1Vjk1NjUrbFkKLS0tIE5xQ25SUTI4bjFBc25WVThneGxH
            Q1FsQ2FOQ1hOT2IzSEFtZW5tQlVkeW8KTPOXOQWlxDQL6cSsn+ezqtDM61om20BW
            AppJ0rnCYqu0Z4LA4nnfHIWrfjsBMdXPVSaFsuu0NBPIOo2MD4Yytg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-30T17:02:00Z"
    mac: ENC[AES256_GCM,data:F0ZhhvYLrimua0SlxRJvtBW6ARU209xVk6FG1z9BSYUlr9zB0JVg9kcvQ+O6CzrU5OMGYJpiJJJN6ZR1+mTJ5mWVuH35HVzpIIV8UdSzpOWGB+jJz1n3a6FQgOsPD1Lm2yvJfmUNPMwnaeI4xm4NzL2YjWyL0ivuMTR1Pa/SJoc=,iv:kSLv5vD9ApcgO16HRJ+sa9TXru3mLpMWucZ36cW6les=,tag:HihI4Efg4PVImNAspjMcmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
