# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData:
    id_rsa: ENC[AES256_GCM,data:NkmYJug=,iv:/2Qfqi60i6H/Y24NKADnpBXDvV+123V2aFHv9y7/Bdw=,tag:yQruVTOYC7P+xGzKMPTNDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bW9ZVzJJYW9uSzdGWUFF
            NklaWVZTdkt3Z0NwWEpndnBmdXlXbDVLMWs4CmY1TW14N1dOZmNHd0h1NllIZG5j
            UHFvbDFIU2ZYaXRIRTVEV1JOdnIydDQKLS0tIFEvRWlpUlR3cFU0SC9iWXlYOUE4
            YU5uQ0syNmVEWHhudDk0N3pGZnlvamMK7T+EApsX3OV2JghQ6KEjGBE71+e+iVSM
            guXyOOxQpD0k44cR5GxP4fTqxHi/MNFk1P/uCePQeSmt+0hHpLXl0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T16:15:22Z"
    mac: ENC[AES256_GCM,data:AsWQihsU60k7GV9N27kKxcIxufEA1cEp9OXjS+kRpwXgXHN3vyuuEad+o5HA7LGDXKfozSh0ZY2Ump+p+szZO/aoGPQamIXEDmMd2LXm2SJb5EKhAZchMKVg+aW5EwhM1iOJzk34NoMDsFz+G0xaOOrod/asN4BwfRsZm9eUjtU=,iv:hDt1U8Lp/TIynFgXWnceS9fxISSv86e7D224cvZPQsY=,tag:uvdNAJtnM9MBWpQJ1jOBAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
