# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData:
    id_rsa: ENC[AES256_GCM,data:s8Z6vaM=,iv:ZHuGjAzm7Btpvw5iRVUWnU93aotJL5E+bwED02T++4c=,tag:G2bT7DsSIt+r2gs1/OiO6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZW5NMlliUDVRZ04vaEFK
            OHhjWFN2OWhPWHh6WFJ0Q2thckRERTRkMDBrCmZiUG5UbTQwejRKRUZyd24wWFJu
            M3hmYitGdVBSREdLVXNNQUpBMS9XRjAKLS0tIDEwbWhUeVM4WXErdXdCUzMwUEZE
            SUFwWGZXc25FVTBVaDhsZE1lYmZZTzQKv62HEhk4mUCEYpuMnO/BuVwGt60JXUXB
            cqGuorHu4nfSgCc9UpGYQG3BoWToPIzKwTVzE0KiPQ7AgeVM2AUSzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T02:00:33Z"
    mac: ENC[AES256_GCM,data:cTl8uk/NieL+t0zoEr51AX4Q1PGEd5oLlUGDlCmBQAnmwavh+9x2LPjNSnzLWrS6kBWMnIXrBA0X9ZBWOPNg42Y+SRo3sJQHBUdgFOCNEN/2Ldr7smfPl6FPEaEL6NtjIvFsYbwXyOoiBOuW1Rqy5+KDkhCYPYdOS6uKj4eynw8=,iv:/cXNbaUI8EYox9S79m/jQ/p5z+wiNgdKlTYjKTPXZ7M=,tag:aMdfZZTd5fk4sQ0Nz6qJ+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
