# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData:
    id_rsa: ENC[AES256_GCM,data:GbvEPFQ=,iv:DCNLgnZRVV47lSwG6c6ZDlgS/mRoX8BRoi7XFRK6g+k=,tag:NrdP3EbQprcfKt3Bba+Qrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Kzk0aWVNUC93T3YzUEdk
            YUpRRnYzRXVFOXMwVC82MXpITERKa2VuWUFZCjdOL3ZyZXZZdllVY2RVaUFYbXhq
            RHBqb1JlcXNHa2dmY01qL0RGNk1JZUEKLS0tIG83bWQrTE8xV2h2elZ0dUNFRmFC
            eU5YMWRseFpkWHQ3Y3RhYXBsOVA1c1EKcz/BDaigoE14Z3Qi7NVfHi7ZvicxdYlk
            qFd6k5CgLTMXtovdbAfWHl61Jtt0g0idc2jsQ5NPLeIJsK64N+Zd0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T00:44:27Z"
    mac: ENC[AES256_GCM,data:reFniUV2JYzwq88rA3X1hxruHs+Y3T5ZJjcQ1bV7R/78OdiGuRXBxn1wBOwBWX+IoKIlOYS+HuCQx+h57AFa83iStWaMj24oNJ5XB4BBVoN0f+d2qD1t1PzO0nj9EDUyVZPGPSmA2Asa9Jd2f0jEwBWrgOr5x8v9pOcC+vxy3fs=,iv:cs6OQfyJ67s3ZGfu7+IP6LL7rTg5m6ZhsHR1rzJW2/g=,tag:2Q/SHLyByGPBQdSor6FKiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
