# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData:
    id_rsa: ENC[AES256_GCM,data:GOEpWQY=,iv:np1EOT9amwliSVov2qOQ+4NTjOFYw6NNSEWRmkUzkxM=,tag:VA7/AcirjwX5VBnj4bFV8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScVFTanA1VGxJL2h0TmJR
            SUVpSkdjU0JQbkhacWZEbVNkRVFocXdreVJ3CjdDYnFWZXA2aEJVcUEzd1I1MTZS
            cENCSi9mYm12WlhWTXRRaVpNL2VYY2MKLS0tIEEyWUhIQUVTdnV4cTRwbFVUbnZQ
            MkRrZjQveHF0OG5rSXgwZkNlVHV1QncK9erV+I8ruEksgHURYLVSUDaOMzabd5yT
            iXO+xmsmh/qW5pVKVvzzkmb8Qa0PgvK5z26k0nQDw58jWSDAp2Fj8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T01:21:45Z"
    mac: ENC[AES256_GCM,data:ARmBr3ZUQP8SYaaeoSsmgOBgitOwaCjf3PL57VvVHcA5uVe4KeBCFvO8fcOBWTFuVwIARPVK5seRK0GhyZg/Vk1M7l2vVE9z4QUTVlfsq/WNXn04PYpnvsOgs50Ss/9bdCE/nU1A54rCw5a0wd9xuxOF7eKQfykE5fRXWxTOFdA=,iv:JytvoGFDqgfzB5M126d3jEuXmLrYafsgTUaKwaypMKc=,tag:VxSeioNi+oXs0utP1VFYYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
