# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData:
    id_rsa: ENC[AES256_GCM,data:PQUz/uk=,iv:+vG9+9w79F5QIhrh+sj7jIW+L6uGkENVqNBSEjWI5L8=,tag:tWiExULT3usdzKRVHboIBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQVUvVzI5SUFORmN1WXhO
            Ym5VeVFCbjU2dExhQVZzV0t2dko5aEhuR1hBCjRGRWp0YTNzalhjVUVjNjBISjQ2
            eTdTeTJoei93YVdWaFlnVFpRdU9zTkUKLS0tIHRjU2w5UTlVdi9RN1E0eTJPNi9J
            K01YVVRtSHVsamd5WHNqNmk4UUtsdjgKZqBqWVfUcH6YmVKSNLTr30hVUkyR0qmS
            QBxL67CeoSJOK+7MSMfzueJMBxiWnm1ZzCW8YXsHQBa2CGpH2rJXEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T18:58:03Z"
    mac: ENC[AES256_GCM,data:jMQrmro6VNF2i4DwhWSsN36T2f4JMKl8OfJSila8dLfVvGZdfEFXOZGOZMeCTvc0ZPznHBCqAGIk1JwGYc0xbY+SreOeiwd1QbYsJ7LdE2R5+k3l62hIO/RzJEISrciP2L7uaOys0Xq8TCyZuulh+uTR9UZ2qQdjLK5yC9CLWMU=,iv:KrrG+tpeg/B+vIAM2/JIGhlQhZpaYMaVURkR0gvWZKg=,tag:/2VUHDQA9/W8LcYYF5fHaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
