---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  dependsOn:
    - name: mosquitto
      namespace: home
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2024.8.1
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: home-assistant
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_PRIVATE_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/group: "home"
          hajimari.io/icon: "home-assistant"
        hosts:
          - host: &host "hass.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    globalMounts:
      - path: /.config
        type: emptyDir
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    podAnnotations:
      secret.reloader.stakater.com/reload: "home-assistant"
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.6.0
        env:
          TZ: "${TIMEZONE}"
        git:
          deployKeySecret: code-server
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            hajimari.io/enable: "true"
            hajimari.io/group: "home"
            hajimari.io/icon: "home-assistant"
          hosts:
            - host: &host "hass-config.${SECRET_PRIVATE_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
