---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: restore-ctrl-home-assistant
  namespace: home
spec:
  trigger:
    manual: restore-once
  restic:
    repository: home-assistant-restic-target
    destinationPVC: home-assistant-config-v1
    copyMethod: Direct

---
apiVersion: v1
kind: Pod
metadata:
  name: restore-ctrl-home-assistant
  namespace: home
spec:
  containers:
    - name: mount-restore
      image: ubuntu
      command: [ "/bin/bash", "-c", "while true; do sleep 30; done" ]
      volumeMounts:
        - name: restore-ctrl-home-assistant
          mountPath: /restore
  volumes:
    - name: restore-ctrl-home-assistant
      persistentVolumeClaim:
        claimName: home-assistant-config-v1
