---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wyoming-whisper
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    controllers:
      main:
        containers:
          main:
            command:
            - bash
            - /run.sh
            - --model=tiny-int8
            - --language=en
            image:
              repository: rhasspy/wyoming-whisper
              tag: 1.0.0
    service:
      main:
        ports:
          http:
            enabled: false
          wyoming:
            enabled: true
            primary: true
            port: 10300
            protocol: TCP
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: ceph-block-hdd
        size: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
