---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wyoming-whisper
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: rhasspy/wyoming-whisper
      tag: 1.0.0
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          wyoming:
            port: 10000
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
