ansible_become_pass: ENC[AES256_GCM,data:rSIUKwHeirbA,iv:At9qFZRyo+y+ZUEI/o93zVqQMfeBAclCIh/DoqImU6k=,tag:uX1HFQlz2CAcj0BRoI9F5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb2VnMzN5dVBoT1lFU0tX
            NFFWYTIwQ1MvQTFsUG5BMVRpVVlmSy9ISWhnCjV0ZGtKTnoreDlnNitjcmlIUmhL
            Qm1sMVhqc1NlUkdLdGZMSDltU0V5RjAKLS0tIFYwSVZ3b29pZmFCY2dWeDM5T2R6
            T29XVzVKVkZTSUhMeGQwckhtVE1HM00KGxAvAdsfXMWfe/I5K+fH3tkHfy/ZrG2J
            kf2/oDgUVPuiSsOhy+FC83K2WNWWNc0ZL0V8TztnudBpvyseg3zDRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T01:21:45Z"
    mac: ENC[AES256_GCM,data:x7/XC+c/dBj1Z/Xn3Hfsgxqgczvm2hONFYyZ9gFoT0l5IYBCStUmkWsTSWZ8GlUdYnkbf5ycmuAaferuSbKUCXSAcW8OKThDZUzwXo+1eUCLTcw4YPAo/IM7Pp1IjtJF4jBPYcDsfHfliDWrZSN8xCsz/FInhhgtZwqemXzsijU=,iv:QEOFl+fYAiMegl/5hCLprBzM9n9O25GW0av4T0k2VOU=,tag:SE/iN51FDSLZPg+tGhxEdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
