ansible_become_pass: ENC[AES256_GCM,data:vJ07gC0a0qwP,iv:6gb/zt1hGYzvCQzZSB9eB84A7ZMAdYF9yvm9keKs6eU=,tag:97y56EryFeOz+IA3CAsN0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUVFMNDl5dGd2cnZheWdm
            bWxKVmluREFJZjBwaStaV1hzeWJ4NTNTeWl3CmhMWUZrdkNVb1Nic3V4OUQ3NjNC
            TFlyZVp6U3dtNkxyUWR4Y25XZDAySW8KLS0tIEdkTlkreGF4RHp4UFY5N01IaHBo
            SG91eU1PVmtBa3JzQTIxMDM3ZU1ONlUKHUetMT/lMxzisLPMWupKd237Sj4y+CmB
            GWyY2eJEhdBohav9momNn36xOPuZOhrxrs2wPEbqWf9zUOjlYywVJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T18:58:03Z"
    mac: ENC[AES256_GCM,data:XMiC2On1jf9X8mm6EJ86zGKhNfTMxk0/EaRl1wCaZDx3LsLBa4ucwRZoAwFtxNFZ0Xk8xj52iEvPOvMumGvBVPC6fN2275E8FRkhjRPLAWQzscNSuqemvCz+pDIuOTA/mNmA+n2L/dSOJNpygbwPRAv5KHq0kOcs7xb8ex924uk=,iv:J8NdduU1p9qPsGtfd9mQZU07C7XErCBmOrcsq4GQDCM=,tag:Zt48H1TB/Ou0iZtjGw9STw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
