ansible_become_pass: ENC[AES256_GCM,data:QWIybZZWwVOx,iv:V5Vyl+yg6LBseTZr/pcxEhBNuh6Lox+xDfYoxwcqQpo=,tag:sRM+rH6aoyb7MhjzFeRm+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraXdicTIzSDcwd3FvODJ0
            cnJ0SWF5RllzM1o1YlU5YlRVa0J4V3RqNVU0CldYcm1rWVJSSWl0WmdmN0JoczZh
            dkFiN2FsWGwvdkhGekhURkR4aFBvVzAKLS0tIG1kVDQ1WFg0enZJd1NuNEd0Znp4
            ak9VUXJxOFZsNG9nQkNQY281LzhWQTQKlBPBSTRrhPvdq5tUQ7MhAcf5ObhV2PkH
            WlUuGJ1OD1nr34qriEFJ1ygMkwX8khsmRf/4X2BNaLTHCbEHrvsm+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T21:32:57Z"
    mac: ENC[AES256_GCM,data:QMsQlumb3Q3nfnKOtmN1Ytc1PO/Y4b2o8IKzvcnjrncRDglJ/1n0M698uf8AUPKzNseh9A1usuAgQg1puLF9dImSpnxKzPeD2XGh+6BjFB5e/Jn7Iauwo/k15dZi/TvDHk6Zlt3QB+WVAgwYPXCzdftx1/k61NF7lEIqhEbA7Qs=,iv:Njo9r+w1SBIgLczwHLwRWYicQoFL7Jx671g1rru4tU8=,tag:IogEALXHSM9RhXAGoCQfWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
