ansible_become_pass: ENC[AES256_GCM,data:K19N/h5Z0GBG,iv:QLZmhUUje3zdDTCA0LQrQjQoJR4r0dgjQMsXWZBKKiM=,tag:EdOWe4ddRP9E/2pkmOLw4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdmszMThGZjF3M3E3Vmdw
            STZwZDlQUVNLbkZYY3RmRHFvb0hWc0dOSWlJCk00a2RQTGJVbjI0elZCcUJkTWww
            dHYxVHRXSGlaK0xhTkN5dDdrNjgvNXcKLS0tIHVrSFNNZ25tYXphYnFmMkZhcmhw
            RjhpcWN1ejRGaE1rWExaN3ZTdGRncVkKgg7PrI3BMPGZOOouiPCLVuBWwvtRAoj5
            04JD/87uxB4Rc2CCqJVUraC/mByl/smbOUH7xsZw0HqO1mSqsHnOvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-21T01:11:38Z"
    mac: ENC[AES256_GCM,data:x1WU9PElLD3XMbST/WOpuzq4xFaNZSjuNFgH0DwNJdQUQCFRXd8sIGngE+xtoZYE1Jp0+cr90uJ1os4q8GXrtWmIY3d2aTLG+tBeapaK2a4CUq3/qBsE/BZCfWAjOnpIk7M7o6zgKc+VHXPi5b3pIJ2hZRcD58dr9CBPuHwwc1o=,iv:2t+clbFR1Vz9QtchCrqh2cS47MugHms248KNt1zY92g=,tag:jQcHiYZ+77nR2On3sP9SXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
