ansible_become_pass: ENC[AES256_GCM,data:51ZhaALHmFft,iv:1NzXa68JMJXVw2zCcxEUOMO+JgkkhCjxw4rPiEqJZJ8=,tag:3Le+6rfYNInPNLMOSeMDGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUEU2dTM1N2w3Yzc5TWVK
            dmRqSFVZMURHNHduVDE4cUhGb01MVVBlMGhRCjJuSzRIUisvc29Ncmk2cDl0cnRt
            OEMxdFFJTk5EN2xNaWxvSFlJRklsb00KLS0tIHV2d1dldEttMTBUdUgyZy9PWkQ2
            RXk5RTRwOXI4UDBUaTlobEZMREJuejAKTbm/CSKhciAjxeB9Iugm1nuY6aDsIaZj
            MKhjxPYX01YFQirR/aF81WAnhqm82va2kyREfeIb/9TvjpQvLrdhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T18:58:03Z"
    mac: ENC[AES256_GCM,data:PD1WZZoZp3TafSqoR4lJHP6n+2ci9Dkr+5dXxYIgMRZyJUvYp9uYpX6xMZGuuRIfqHFf81jNXSSic4BtEoSe7jYOIIQu6UU84+cAv6nLVt87riQfH2FuWMu/acAuctqCdC/Pz8T/lp9Iz4PREXuWWHX55ikb8yOvrT2TruDsQ54=,iv:nw0zj8PH/1pXeIHfhT38q5B4eZRG/Txu/1gM6t+Elp0=,tag:G5BGE1WMk6NG6mjyKA2nxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
