ansible_become_pass: ENC[AES256_GCM,data:9317RmgFkpSY,iv:WTlFRA+M0bzsQ7QKfFPpxfrIo7gjHigwn73X0XyTcHc=,tag:yKMuZJCNkS62j/B0kPcDLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWmlRS2tDM0lHMkc3djIz
            VSs0V0d4UExFUkNCZ0N6Y0lyb1BPM2VvNEZzCjd1OG1DQTcrdzRldS82dVo4N254
            RzZrZytPazJLOGtWSWVVdjYzS2JxQzgKLS0tIEl2OGdZOERJZkJMWW5uRGYvYUts
            Yzh0SlVuNVdzZXE0N05qdzBxSXFFYWsK9aQwK8z5ZYyhGCO2AP8k6AP7k8J5npxc
            Yl2hfo8uCvi2kKLXC2QLn3uFr2WbkJVNYHemJK0ePHLZyF64hdP17A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T23:29:09Z"
    mac: ENC[AES256_GCM,data:Z5OUOdfuhMZEcenk2rJ7UcLJ8lRoiaW+CbNA28+5Z9O2cimjnj/jIK/wibwuXOTAdb8N9a40v/eWDgXcLhWXe9tDwRdhAd0Nn9KRDqeS4XRTTtxEL1+OiGUPbyrCBZe9T+LUa98nMffQFvQFU7okrf4zqxwODBE/2TBiSeVBJWQ=,iv:bf9AyeQyMMcUMEGjJ7zABELtarTdozXkvGBWCBBeh6Q=,tag:6lBia0Xow6zdaAgrrZUdeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
