ansible_become_pass: ENC[AES256_GCM,data:fL07VFpwWkf/,iv:AdvAhIHUXxGYaQQdXcUcP/vAAbtZsOtAVd0xPWXKPks=,tag:SApie/xr+cyv4M+Ls6fKWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K3JqblUxWXdHUm0xMWtB
            d0laU3JvMFRZcGt6Nkg0NFlIM2FGZEszbG1NCmRNZXZBVHhZYm41U243UURCSEhX
            RlV4K2JXSzhvNngvbzJnV3diVmEvVVkKLS0tIFRvaXNLeFBvaHNPREo4TE44SHky
            Zy9NWXY0S3oxWW15Q1VTN3lqYURlWjgKpRyIoi2dg9ZUg4MCUpbl5d8BGFJqfXVA
            lW0boXJLCYlRaV6gB4mIUHZMygAuZIwabJtgWvGLRsfljJD3QazogA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T23:12:54Z"
    mac: ENC[AES256_GCM,data:SRVyWDZIiYv03oRwkhMlf0oV839/Y5dd8vYr7n5NtDw4pJCS26ucpMtqJLpDS0gbqe82OykqzhhwG4mns+46ePwkqfnaw8ZqFI7ASgmRXIAtcAYO3WsyECaiL9pPi2+COpslqX4QvgHnwc9JFCEWIqxoQKYLKPAOhQ9y3fx0Dwc=,iv:LcA4q2+ehHIF7KnFksfys7HOYHQoDsKRDEGNer6kAJo=,tag:gF8XNVgbsIHTFxU+69nJpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
