ansible_become_pass: ENC[AES256_GCM,data:hJ4lQ7UZew3n,iv:ktjw6wqTS5Ye6ENIM92YqSu7z5I1ueXjAaxZTVyaqHo=,tag:IlAZHNI3wLCE2zKRisy9Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVEkrOWpucXFkTFBzcHNv
            RWVLQUF6bzlFcXEyQjd6YVB2VWtWdjNXYXhFCm5vQlhWc1Jnb1l3czUrTmpORW93
            SVJiWTAyRFJQdVk0WnZrb2htOThPa2MKLS0tIHJ0dk5zTCtZY3RuYzd3cEw1TEh4
            NzF0RWp4TUl2TVpzNnhsT211YUVJRGMKE7RpY6gAqVFCWBdQ1zOz4gupXcHThF/2
            NpBrici6XtWv/liBWZcDcliPPAJaofAFFHKTwSbyrya/tIXZhFI/cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T18:58:03Z"
    mac: ENC[AES256_GCM,data:wJc2zUz/xctHNYu4TN/cBESUquPhsQmgEVnTyVp2/Su9JgGVZDAEJ/CyVy6INf2sPdUjomZIE8B5VK31LRWXBmVmflBWkmxvi6J6tAIK6vNGzAVtMoWSoqPQ7BilUWSnavbCuzYuu+J2m1HfOxWCFw/1tsx3611nmmbCERKOQpk=,iv:EALQIZVfI6ypoIP5+GSmV3r/YERC6rps4QN/llEm5Zg=,tag:bByzc69XoFgbrQwBv5kRGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
