# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: recipes
    namespace: home
stringData:
    postgresql-password: dGFuZG9vcg==
    postgresql-postgres-password: dGFuZG9vcg==
    secret-key: NGE2ZDVjNTBmZGJjZTk5MDk0ZTBmOGZkZTNmZTY2Mjk4YWU0NWZkMzIwMjRmN2YxYzI1MzQwMjhjNzE3Y2M5YQ==
