apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:DehtpkcsgnXW,iv:QmyGC0ces+AtZWaGYMXLAevDI5US83OQ4FZrK1zuD78=,tag:2vCLZsfPQHtFO80aqdcx4w==,type:str]
    admin-user: ENC[AES256_GCM,data:dLA7I2k=,iv:EfBYWeM3t+1WkG+vF0A6KXARLFFdhiY6tPCpWFHrAno=,tag:ThKcAkmsk5ofrmixtwrD2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ1Zrc0FKREl2cUxBcjF6
            Z2FPU0NTWGMrQ3dZQ3pHcmV4Smt4SW12eFFNCmV1WGJ5MldOL1BQdnpRZkZLMFV2
            WWJQMXlhVi9hcUJhWGpXWFFkNGhYMkUKLS0tIGd0TmkyK2EwQnRxU1dhekFqTFh5
            V1R4MjE0VGlVNzN6bUdQaloxdm5wNkEKLdr0SK3Q6dI7zmC3Lw68GWfGEZgQ5zY3
            y3GReaPv2Vlkvhgh2jUq2GZe+hqbn2WUrcdRmqTVeEJT0/6ZhyR4Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T23:12:53Z"
    mac: ENC[AES256_GCM,data:i4sDD6+9rIjPApMh6eGOA2gFl0s3fx5ZYjbDUDPsulkW8DXSTAz73OAcVKCR/tGXVCoRrVVXzq46H3vDO5p3WKj8p4VnzPf7qb979kE18/jzDIDaLWHElnxKVYPLCOWOLkFMEDo9zkgiHdbdrz96hd6PhqlJKTUiuJ8xVHfFTdA=,iv:kCDJ0EbpAmxjb+ziNf4u5Z36cMJ1qkwQCFOVkB83EIE=,tag:1hPkcLFprGnmLWzyEWO3ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
