apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:DwZ+QXWM3/ih,iv:wYSPjIt6CfaRrKmjCE05Jrs/YcYEjvKOBAFbsMY/mwI=,tag:tkjkOv/psHlrBuPQxqyzjw==,type:str]
    admin-user: ENC[AES256_GCM,data:2SPTzMs=,iv:33A0AdxQ6EF1ixfdmvbyn/tKhjxlUiP5V8d6j0IzUGs=,tag:yeikd//sM8BZtMFm4iU7YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV2hpUm0raTNPQkJmZ1BN
            dVROQjUydmI4dVo4WGp0cWFoWEEvb1NhZ0FZCnd6c1BCc2JkQUprc295ZHl3U0lB
            SGpHZFVNbDlHTlFiM1ZlZU1pTFpEOFUKLS0tIEozK2RGWmRxem5OWVMvSS9KMmdq
            RjNySTh1cTdDdjFWZFhXcGZPRmRlUWMKImbzdWBD4Jk/ONYwwl+MS+dScJjIdEOy
            D7ee7mJMX+ZMH3Uvm9mcxyF5/IPo8bxy+dDu14cx4uYkYTaS9MnmNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T16:15:22Z"
    mac: ENC[AES256_GCM,data:h2v9i8NX0DXtmi8BiUIG7Y6Bv2n3kdQ3IqMbuV26ZffPeahnaRaq0supSLjydN/E0eKwYSQcdy9UjdmDIvSX0AwDfYwhs44gemWIWT6qPE2KMI9viZV18ySlnhzP+1VxlXywVlOziyNcluIlzLM3zObe4ShNzbSNLKaKjlmb6FU=,iv:amKUotV0MDWjAIUT45/x4/NFUYcb9DsdQuOeK8dVPyY=,tag:BpWbVKcQMN8dAPaiqvXlWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
