apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+4V3aPd3YJRItqB7MT6lpWvsq9954bXi,iv:+e5iZTzVLvXeavU1aVTKVUV6H65qVtajCqXI0+fjOGM=,tag:+55QKvVOhjbeogXC4AGN6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1enBXWFhUcEkwbTdGc3hC
            amh3aTE2T2kvZzA4L0tWZ1dpWDg3L0c2UW5JCmQxSkNUOTNiaVhoSHJkRXdEQmZP
            cTVQMXp1bm5BYnJXeUFFTHE5UDVYM3cKLS0tIC9lYkFxcm51ZnJZejdKWGtyTG1M
            SmdVcDZycThvZGYxT2FxY0lPOSsyUGMKUS+Eqk46NcU5JKRdYI1WA1Nlpf9YmE3D
            MVbZgGcvEtdhuxo7gtXLkXfpT3gxaPQiG6jlgrg5pZHkyWmgi7IfWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T21:32:57Z"
    mac: ENC[AES256_GCM,data:r0700BBR45IfF2HqeqCL8M86igD7ul3R2D6XJJdMQ/mDw0ceL1fORTdgcFWI71qnIoKVP2C9mZGrHqnZZ5QZMgNpgn3flijtnI0PwCPga21Um+yYA+2yL9+NjTDIajrYkQTwRREX6SwOXauDUDbu9wK/XPPsA6t+VJVPTiz5fsU=,iv:3/omWv3vx95wLPPNhuyOAusDtY/9691EH9jvRny6Ekk=,tag:P8Vr1MSmNVVqx+3gBMi6Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
