apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8FYu15qlsngDtGFvCatsO73pDXyhNjNs,iv:mj85cKk12Mtn8LE1CUouT4KiXCMxMzJphwPKFz5ZQ4c=,tag:gwE/VN3kUBIrkZPr+OQ0WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SnhNY1ZTOURWTmJmSGdV
            L3JKbk1wQ2pwRkdtdExSUzlQZVkrRFZDZVI0CjByZGpIeTZmTGRmbW9UbFNLbDc5
            bkVpTFpOMkhnbWpVZm0xTWVZYzc3VmcKLS0tIEx0UklJRFU2bVd4NUJ1TWNKWlhG
            azc1L3NxVXZMTFoveVQrcVA0ZnRYdkUKSFr5a95bCTJFGAzC8p8iXw6EzF0FMqe2
            Odjoi6Dy03MpLCMyzp0vLopzgV/QRar5A1Z+iCCFX0KB1SKf3Iz+Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T02:00:33Z"
    mac: ENC[AES256_GCM,data:+ebyvwtJu+3VHHJri45Jio4Ux78OhbTHeN2LHtook2OH0siCpIVhncvtGWUGqTL+vw8TMsqAjNjQ9BQZ9urxzqXnoaD5rqenkv9/mtcQJhOEm3/8J9lvOmXW0rpjkgtEluJjcHw5UV1x02wasBh0TTj9cpumWe9Wxj6wud9Ni5M=,iv:DQ7T0JKV0xzsa3encdSIVCeBfF7aSZNWLv3eItMgwvI=,tag:dllQ9EzauW4VrNayXbA+FA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
