apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:a9bS/eaSLu4HgciMMMfaFQIYb30BAvWU,iv:Wd6hLrqbOT9mJtWTBG6i/crzGC9GdnbrdbLW0CMiE+A=,tag:HkGlBCWgiQ8XED77M9lAIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRlA0VUx6NzFqYlh6Q1hm
            LzVkc2RXTkVGRHNtaVdnejBGMTVLMytPY0FzCjdidkQ3UHhSRWJDaHVKTmhYQ3Br
            SDR0Rzhxd2tYUzFUeVlBblNyVVJXK2cKLS0tICsrcVJNeVhjeWZIenJ3NHJES2lF
            RnpYM240bWN1d1hFWXN2Qk9Xb044N0EKEaYfVWzRfg+UBUBrIC+5pKydfqTG09Gn
            pT+XzSZTvmojvZzEdvvmiVdD7oH2b3W6x8WfU8I1F2ArIOarAopA1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T23:29:09Z"
    mac: ENC[AES256_GCM,data:SXxkjVQXQMDCttJPtL4/ZsXVkZ3kjbXVIIN6hwFDg1pY+gNAqsOvlIheFTiLHxRuOitHsz3nBmKMtiTbC+tFi1eBqzl2n85opVWhlezJrBO98VBxt0Zanctxl4yaQOrRhTYTKKqv6HKvgG/r17JXmkYXQJfq1mOfb10X0iBoyMo=,iv:8YpDV7Y9T4Pn5bFYESvA8Auwlef/pXG88egW+vwbtnA=,tag:bGBuNsltQWmy4E+IM8Ny4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
