---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/vaskozl/jellyfin-server
      tag: 10.8.13@sha256:cb3330ef098055d53cefdb2fb26dc42aa66a593c4f4622825701c875f60d9b17
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${SVC_JELLYFIN_ADDR}
        externalTrafficPolicy: Local
        ports:
          http:
            port: &port 8096
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_PRIVATE_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          cert-manager.home.arpa/enabled: "true"
        hosts:
          - host: &host jellyfin.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: jellyfin-tls
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        - 44  # video
        - 109  # render
    persistence:
      config:
        enabled: true
        storageClass: ceph-block-hdd
        size: 20Gi
      transcode:
        enabled: true
        type: emptyDir
      media:
        enabled: true
        existingClaim: mediamega-data
        mountPath: /media
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        memory: 3Gi
