---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.11.9
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    ingress:
      dashboard:
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "monitoring"
        host:
          name: &host "rook.${SECRET_PRIVATE_DOMAIN}"
          path: "/"
        tls:
          - hosts:
              - *host
    cephClusterSpec:
      placement:
        all:
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
      crashCollector:
        disable: false
      mgr:
        count: 2
      dashboard:
        enabled: true
        urlPrefix: /
        port: 8080
        ssl: false
      storage:
        useAllNodes: true
        useAllDevices: true
      resources:
        prepareosd:
          limits:
            cpu: 2000m
            memory: 2048Mi
        mgr:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
    cephBlockPools: []
    cephFileSystems: []
    cephObjectStores: []
