apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:pLI2gaJiPB2fT6UEckYZSXCCAzyYBKfzgCFxrAsE6mGFcc5gp0jykg==,iv:mV4tQTE+e3C8+clUvelP30C2Mkc0QaCDnkvVMSRlTvc=,tag:GoPjRbikCr3QD9D5fQlIhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0amlTVjVZK0svQVlvMits
            RWR5UXdYNTZ3QXBJc3FIZkY2bGx2MWlKNjBnCnUyOGE1c2NRR1VmNjRCN3EvNXJh
            M3RDNHg2UmJFSmliSENBZStsRVBzOGMKLS0tIEhZeU9WTzl1SnM1a2dLY1FRUWJj
            VXB1aWo3bjlaR0pueE9YU0dpSVgxOGMKXg6BSD6DMmqjLPEI7KZugHfy9Dsk4We0
            p8+Xr+Y2rUs4Hvc8ii3TrhCbZL8UI3YmRyWRJ1/84+JN7IMzWHZtQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T21:32:57Z"
    mac: ENC[AES256_GCM,data:Cvf21vIkKwwNVKydz6yt6uxHGIzM8F3xFQGRy9H8gmmnRQoOkbSJ3XjhNzMj3hDpDVlynx3O8IrILnOzPpq8TAmI6kKyzNyYOqO67BlvsS9eVcA6o+GLJ614qTwH8o/EhNS+YydAlafD9K7oPQ84aZihVRwqwdebB5NgI1gGAQU=,iv:VK1Ugmhh8llylo1BBnA9lyzqcXKtsds/a8MozAohHaQ=,tag:W9lhy74dA0EQtur20J25mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
