apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Me8RLZNt4OVurjxTYuGU45WHljXU9FcCaWfCGBOvgojxhqRZqy+Hig==,iv:8M6Us8jkZ5RoEehMCPHYUQ1s7nqy8XSCqVIiH/K1lkI=,tag:JYSRnTn66iJ4v9wU3gnQZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVW0vSHlrdzhVdDV0Q3hL
            TFJsUTZlOHd3citPUEs4NnhyRjJwTFRjTEc4Cmo3SlpGNExHbDk1NEJkLzJqTzZp
            VWVXdHgwR1JoQm15b0FiY0VWcjRRdkEKLS0tIG1YdGRhZlZBMWMxY3pLMDdlQ0J6
            TzNnM1NtVGxvNTVFcHJtZDMvLzZRL3cKY3ONxmLb57aKcsh6kX+WZr72BQZsnWIN
            9+cHlHWtmgH87bT1FgambJuVtgpA+afGrzpwBnB606Mqxlj5fNtYMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T21:55:03Z"
    mac: ENC[AES256_GCM,data:jAWy+dSCgc+XBEm1+6Ku1TDjsixXa8geDSAntU9KhletW4UPoQqJS2hRdWMZ8HVoib/ptizLnUGtvUl5LLwvs228AkPitvTT8OrN1gR9+EYylaIzhD07MxECVvnaMBQ9OkcVoQ6AdkMulEh1U4hJxf6dGvTL25FEPG34+xpT2qk=,iv:nM3lcz4El9pgJU1LRQV7J29/TyXpQs2o0iWF1xwwu+w=,tag:KL5GX3C31yEFjzsG0oziAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
