apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:0UMisFc2XU+TFz1toEieCTeazVTJKzHqy7Ib/8dAtU/f8PQWwENo3w==,iv:9V3ZRY45eawBUpQAOzjT52l/WCRX7q9PN7/utXddLbc=,tag:aiavlikeTu5okPMZik8+Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RXpZb1BjWHprVHFDNXJU
            RzhBVERwb0tjWFFZWis1Q3JwQlM4a2diOVhVCmxlaVRNRForUitvcUNHTEczWHhr
            WE9CVktBaUJ5YjU3Snp0SUZLQVJLQWcKLS0tICtpZ0dTN1kwZlJPa2VZZjZsOS9s
            MXlFWm02MlA5amJaNW9CcUpMbzU4K2cKbKRLCzelTxKViexFKcrCMljSkcOcotn3
            IUKxqjtWN4O8QJdHZzusigRGTY2ByWqiSxuAD2YIrKf+eG2dp3zrSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T01:21:45Z"
    mac: ENC[AES256_GCM,data:uTJLLebpuAu8eYqWNGtQN97+Sk2upJ26RbCC15vOlOtMf2h1k7LQzdZgV4XbtBX3J11wBkff5cuNsG2yzI+nnJvr+zDo14TCet0Xq+/854/aRt8joWerYLengQIrudyY+XgQlp79CTxIga9nGTDCaLlYaxXCli4VySp6aFTO3Xs=,iv:XGUTAIhdIZRuSOcUYq6DmjxW2MRrMSTmqRz4AiKEHRA=,tag:bbt/F191pK5SAVGHX9bk0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
