apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:2qOZcPtpwGo3vdGyKc25Cj12DHJwbZFlL5CwTQhjcnMJiKAA3RV3Qw==,iv:EO4yxrT+LfBpz1j1n3YhJoyNpYnSUsX4v46jn+bmRM4=,tag:L4j2YFPhvSW9N3Y80+Dm/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNWJjanROaTE3Y2pzd3k0
            TjlFd2tSQ0lVVFJQbkc5T0xYUjJWRVdxTUJjCjNkQWpVV25sdHFlalJwWnlCbndH
            L0p3dWFFYUpYcTM1RmVXUVlLVm0rTFEKLS0tIGRsazkxU2FtT2h3OGpvaC9KYzMx
            R3EvR2g0V1hScnNFNVFnYUdPZWxSSTAKh9vXzLkoTmHGnbANArxc3qL8uMVAZ9WN
            vpOHLK5lh1Pg/SkSZdh6NOHi/ncVVfR07K7zpMnOHI8t+wpH/B1DZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T23:12:53Z"
    mac: ENC[AES256_GCM,data:f09dVpFBcmN2iFFtNbv1PcPZdnbjf9BB3eeYX8y3GXPoDIuKcneKelvQiCqqRrgI562TMKP2sK8eZn7LCTuwzpJAFv0CuxF+WOFG9uKH4y/3rHQtuMfQWCb2CnOfxUPuq9klRgmApNgql1pD8nKR0UUi/X8MFGchdgdRMiEkwTI=,iv:/lbS1jyurlNLHTCMDYd3PZaDniki/AB5bHzHMhPKZT4=,tag:QyeegUIWGOw2LUtCV+9IIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
