apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:unzqCXCDZuXeJpLtOXReWy3Vk1zjOtuv80xGwXkJPJxTg+q1OPmlNQ==,iv:OCND30U8CtC2AyCnVtPRL2uI3LHDtHPKl84fBQ6L46Q=,tag:tpxQG8VEBaOhujx0djE9Dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUFFMbk4zbXUwSU9CWVVv
            MWpzTXBiaGxiTGNwV0l1aGVtSGJvVEFYR2ljCm44eXZ2bFlMSXBQYWprUzcwRzRS
            NE43b1pydkVlVTgyc1VkVzZteWVFb1UKLS0tICtnRUVjbVVIZTNIUmpQWHRWT0FZ
            VjZUbnhia3c5ZEtlTkErRDltSWpoWEUK4wu3ndEuobUjrSM8MFjhAIqO3l232h1S
            N3Zz/XCsbNB6/xsi3eDJHV/uILD7goTkcm2vyFMDP+JGND+61lKUJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T02:00:33Z"
    mac: ENC[AES256_GCM,data:i7S+CxgXwmpmIizWLthr+OCPw4O3uSdW2oyaw72VzIlyvCG79m7O3qzNfQ/eAhQrXVB7fJLGERsfPdPM/5RlVCYyjg9vqx08+7DOy3Ikp029aigOCZHcQjOe4svdonMj406Izdq2PQKWAmskWzECXRGwVcLNxU/JMYNX7Ck5hY4=,iv:KItHz3AIczG8Mr5ja0Uxol8PrJZo1tumqPv+moIv7XU=,tag:4FytxvCewDkaiKTSXjaStQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
