---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.14
    command: ["mosquitto", "-c", "/configinc/mqtt.conf"]
    env:
      TZ: "${TIMEZONE}"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    service:
      main:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: mqtt.${SECRET_PRIVATE_DOMAIN}
          io.cilium/lb-ipam-ips: ${SVC_MOSQUITTO_ADDR}
        externalTrafficPolicy: Cluster
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    auth:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v1
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto
