---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media
  namespace: home
  labels:
    app: recipes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block-nvme-norepl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static
  namespace: home
  labels:
    app: recipes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block-nvme-norepl
