---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secrets.sops.yaml
  - serviceaccount.yaml
  - data-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
