# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: recipes
    namespace: home
stringData:
    postgresql-password: ENC[AES256_GCM,data:SfYoMrLYFie1mBKm,iv:O7vqw7cF9DZ0nia1qvg2PKfEg4Lh70I6Cdu+o7IL1xg=,tag:ot/5EQWaDAqXUICpWTAxiw==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:OfwL6Za6ALPASeAI,iv:vMYf/uBafLJ3kf10RXsgmwWYqgKOY3YZUYHLJyo4WDc=,tag:/+gtleYQ/5NChHJtjW4h/Q==,type:str]
    secret-key: ENC[AES256_GCM,data:e/exSqwJ43ORxYb8DxU1DM318dvAw6nrjePYoTDuhchWWD3E2nbUnvsi03OzRpOCGXdmRPSmPMblMeVc6G2g6b5Bs5RVm2NZIjF5JfFLh8IZ+Z3+HAvNYA==,iv:hdXb3ncuI/8tvtGFCkUvXuZ3tbdo6fGMBvnwyZHIha8=,tag:Co0zm30nVpDF+L2THoAuvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcExGdXdBZlhmWERsb3Vo
            eGUyUWFFdlNzY1cwMjdCdG50NXp3NzZuTGxRCmdPcEpOMmVzZmJmOTFJL3l3OGsr
            M0hZNDRUeUt0NkN6OVBuNm9KSmc2Wm8KLS0tIFJXdUhOempaNkZnMnBtMG1GUVhT
            K0JQWUlSeDRTSGJYZ0lmelpNS1cwencKnTJpEK7mWDOBgGC+oyCJvfVEcCzCQRiE
            gwYv98xZJRmwfi9Wir7M+aRqNFIaK1z9AJmy3NoWpm7Ge/VZjiSYSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T18:58:03Z"
    mac: ENC[AES256_GCM,data:sJgR1zABj8gvod2LQT3NqwlGKIA9/i/di3mA/AhtLZWanGb9U3xZes+osdFGxWROKAnHJ6hAmHmZYSAHYbl9l+7vVwEUusc8brven6+W/kmlxa3SfvSuxTJyOpuxi7bWpGGAEgljYMkUA7Hg++6KqNXXfWP+HZGt77XM9lTcx1o=,iv:5gOT/j9lYIYOAW0xX84PzP9HrK/mdRjsD/MQbOx1vq4=,tag:NkcJ4kScfTGwiSAdB7uErg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
