---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: recipes-media-restore-ctrl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: recipes-media-restic-ctrl
  namespace: home
stringData:
  RESTIC_REPOSITORY: 's3:${SECRET_VOLSYNC_REPOSITORY_CTRL}/recipes-media'
  RESTIC_PASSWORD: '${SECRET_VOLSYNC_PASSWORD}'
  AWS_ACCESS_KEY_ID: '${SECRET_VOLSYNC_AWS_ACCESS_KEY_ID}'
  AWS_SECRET_ACCESS_KEY: '${SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY}'
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: restore-media
spec:
  trigger:
    manual: "true"
  restic:
    destinationPVC: recipes-media-restore-ctrl
    copyMethod: Direct
    repository: recipes-media-restic-ctrl
