---
timezone: "America/Los_Angeles"
github_username: "boundcorp"
coredns_addr: "10.43.0.10"
kube_vip_addr: "10.20.30.250"
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
node_cidr: "10.20.30.0/24"
