---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_PUBLIC_DOMAIN/./-}-staging"
  namespace: networking
spec:
  secretName: "${SECRET_PUBLIC_DOMAIN/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_PUBLIC_DOMAIN}"
  dnsNames:
    - "${SECRET_PUBLIC_DOMAIN}"
    - "*.${SECRET_PUBLIC_DOMAIN}"
    - "*.${SECRET_PRIVATE_DOMAIN}"
