mqtt:
  host: mosquitto
  topic_prefix: frigate
  user: "${SECRET_MQTT_USERNAME}"
  password: "${SECRET_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

# Global objects configuration
objects:
  track:
    - person
    - dog
    - cat
    - bird
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

detectors:
  coral:
    type: edgetpu
    device: usb

# Global ffmpeg configuration
ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "yuv420p"]
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

rtmp:
  enabled: true

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 30

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects

go2rtc:
  streams:
    frigate_backyard_hq: rtsp://${SECRET_FRIGATE_CAMERA_AUTH}@10.20.30.151/Streaming/Channels/101/
    # TODO change me
    frigate_backyard_lq: rtsp://${SECRET_FRIGATE_CAMERA_AUTH}@10.20.30.151/Streaming/Channels/101/

# Cameras
cameras:
  # --
  frigate_backyard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8553/frigate_backyard_hq
          roles:
            - rtmp
            - record
        - path: rtsp://localhost:8553/frigate_backyard_lq
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 10
