---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mainnet-rprysm
  namespace: blockchain
spec:
  interval: 30m
  chart:
    spec:
      chart: prysm
      version: v1.1.1
      sourceRef:
        kind: HelmRepository
        name: ethereum-helm-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    mode: "beacon"
    extraArgs:
      - --mainnet
      - --execution-endpoint=http://mainnet-reth:8551
      - --checkpoint-sync-url=https://sync-mainnet.beaconcha.in
      - --genesis-beacon-api-url=https://sync-mainnet.beaconcha.in

    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
