apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:twHOrV1V1mO3wW/d/i5HLSecuw1C,iv:nv/LmW2VCAUwJaW05fQe8SbaaCZPRnxj9DqgendaSlQ=,tag:1GZ33fSNGzAO6JB/nCvgdg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:L4Hef+hRi8ynY9lIU8mmC/sDCJtIrwEzmobAPX40P3T1KwN6,iv:X3ADrT0GP60bRHGxZfl9ZJ7ZhcdbdpQBslxfSfhMrPw=,tag:CuRfsrEfLPEdNhBc6GSImw==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:Evu6yNcfSBnpw3RbBA==,iv:gkSrIs7Vlf9XNxejSbR808aQlCHo9K3YILsXDfyjKT8=,tag:FR6qitUeGSzXmkhNX1lECw==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:8hmUYIj6zN998cK3k4n3cihw,iv:WaIdcsCvw5/06LH03u8DPXoPMwY7uwxxXMFhOFw1LWk=,tag:jznInCJf3zRnMPe0DUriLA==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:GmDEoY/QMNYUFv4Oh/8=,iv:wpxRxUhB9eFVxkGz+avryNi/3oIeqcD0854ACIHUnFY=,tag:3gtUiKtypniK/DLyIELUxQ==,type:str]
    SECRET_PAPERLESS_NGX_SECRET_KEY: ENC[AES256_GCM,data:IejcPxbuVKQR46H7f3E=,iv:EeqpUAJXndrpRGQxWsc1lKjQTuzLhl15awmA4T+dnaE=,tag:T7Bl7xs4Xa3CmN/bVpOzDQ==,type:str]
    SECRET_SES_SMTP_HOST: ENC[AES256_GCM,data:Fa4i7OSZq4+hU562pXwdd20wpaFDLkV40C3hJBnNqkNnUw==,iv:vY2I4ZpPiyaT7jTI5aIESV5Bri4Kp593H5cyY1AMDkY=,tag:7SXAgufCQNHTgsFTXOackQ==,type:str]
    SECRET_SES_SMTP_PORT: ENC[AES256_GCM,data:nJG4,iv:NtcinkobG1WvQ8GX8gojKhlczT8lZfdWmSZIgHHOu3Y=,tag:zAhWdJxib51IahDZMsKAuw==,type:str]
    SECRET_SES_SMTP_FROM_EMAIL: ENC[AES256_GCM,data:NX3g+11/KgG9IQoGhLaf5Ev972m3,iv:l77QPjCRfultYQDf54ZaEeG4Gk4WZdx9i9teDv+NAxk=,tag:M/SUIp4u5WREuoy/drfWkw==,type:str]
    SECRET_SES_ACCESS_KEY: ENC[AES256_GCM,data:H0mC3C0kVotGxz7Xurrqq3ZNj/I=,iv:bBH91zbuGEUyNutMJ7YfgaNulpB0b+mJ4n1D7xM7hM0=,tag:sr+ihexrJAdSiNcCKXiAmw==,type:str]
    SECRET_SES_SECRET_KEY: ENC[AES256_GCM,data:y6mzMZfXlggJB4wPgpKTkJfSj3eAqDqeTAHuNa5ZOuf7/H+Jly5Bcw==,iv:L+rSH0F8UTB66pMHAXF5awpPf4UntplecU+7+W5hKsM=,tag:yXyXblAyfC3/KcCNYPgO7A==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:lCLK0cQj46yT2MLHcgSjRaX0r4zkqAfYDYaUpbST6ZyqPwp+P+5lqg==,iv:4LLQELw4T6+DM6LIvm49rtomOosDeAT7imsaOtjZalY=,tag:Fvng2QhcB5YP/pgc6kL9yQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:ywQx87rcSzE=,iv:/KO3Ndnqq7n2DkPlk8vuve7KyaOnQO2txIvJwP3+i2c=,tag:sc44UhbzcIszl/ywbVxgOg==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:wE6PpNC/TnI9OrpqVbxI8kbekA==,iv:SQX4HB0S17QhYYnvLVcjTxevH3D3N9TLMSy+05HHilA=,tag:O61u7jvBcvUnwYzNsOlzzA==,type:str]
    SECRET_FRIGATE_CAMERA_AUTH: ENC[AES256_GCM,data:eHww9rT4dKACLMuh0zmdmw==,iv:4vZ6PHugJHlgT2ZYrkOrJErzHs64H3r5+RE57vQaL7s=,tag:e+JNi3plCK+8+MBvQsvQRA==,type:str]
    SECRET_VPN_USERNAME: ENC[AES256_GCM,data:z48a07TLDLrIzGIWHxJYpURJjWcXMzcV,iv:vy2Lv2u3DZ+F4XTqBHgAbQMPIYofkMJqImIAJq1F/0M=,tag:mUT+0poNvMOq+DERfnIKPQ==,type:str]
    SECRET_VPN_PASSWORD: ENC[AES256_GCM,data:sSElJUnUQ2g12Ro3fMxaEwvk9FxFf5pf,iv:HS5n0t/hGAN7py4GBDOVyKKkwRF+mu2KPrWl61p0RfE=,tag:OiUOmZE1h7xmwRgyzXA4dA==,type:str]
    SECRET_SLACK_WEBHOOK_SERVICE_BOUNDCORP_OPS: ENC[AES256_GCM,data:lC+OHGFDZg3EQ9mTB1vxqesDWheccK7FyS80oENLlupVGAnXaSdD7XX2Iz5a7g==,iv:T+wQowuL5zeZz+W73H7XYu6g16YuKSd3m2tyTAo4FPI=,tag:aGsc9hMPehOC25L7GKLK3Q==,type:str]
    SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xtsnv7oSU6N3YhzEDoKMoBrMqDo=,iv:4K6GH2/Ds0Avj7PeiWEt97T6CZ1AfpUW2zFIE3P8B10=,tag:a99REMrG4CIG9y6KxtXOdA==,type:str]
    SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wpK97I1BEp94gZFjoxJpFu47MOvO0ebub7lb3VxcjLrDj0ajq6wLmA==,iv:ATWhUoq+a3RpFva/7svDDIqfbwWObtszqpSGAH4HCsE=,tag:Rx7tqdsJtt2cDCkWsU2OGw==,type:str]
    SECRET_VOLSYNC_REPOSITORY: ENC[AES256_GCM,data:c7/gymuWT1KcX0by77SdoDZ/eyDrtVryxnxbRV3MukVXm07z+2ngoJe6xTRpUkIU1U/gtTwisdJqJdRJGXC0Uy0ZWMyCXJYLCmpmIzNUk18=,iv:jYClsO4tx2fDZOmBk4eHOezeaL5ACgSK/B84xYuwy4Y=,tag:fDFkgamh9O3M3kzTKilRAg==,type:str]
    SECRET_VOLSYNC_REPOSITORY_CTRL: ENC[AES256_GCM,data:6pok26Rb8ol/F7SeHvAbRXEg1CukR9o1XptEiW5X5cWYOC+VIwpO7w0b2CxxV5CkA/WG7jlVYEacKKZTSK3/QWbbtVtxmmnYxvssk44=,iv:j9TfXtcjIfAhcxPj/UIQZUukqLTeTtM6oZTEF8Ybjz8=,tag:w5mqlkm3gAGrM4KnVMhxHQ==,type:str]
    SECRET_VOLSYNC_PASSWORD: ENC[AES256_GCM,data:aBt0iWnlE9lD,iv:suVDy2aL6k3Yz2fl4mT4nqL3Cgjp5yXocnd7N4jMJMI=,tag:h4fgcd+L4zm6yAmvB+06uw==,type:str]
    SECRET_VOLSYNC_SCHEDULE: ENC[AES256_GCM,data:233bZR7OPXqP,iv:apJhYbtyhCndYHDMVDrCWmHHJaJgspClDddER/2LJ0s=,tag:cRSHvi9HLorlIiWoJj0FVg==,type:str]
    SECRET_TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:eFoMHZN/pOj7H9vC+trhv1ACRYmZ3qjFs5moLLmwbiDHwITjMSVQDEtiaiPfgULMoCirJMqCThza,iv:bbkK/VOQI9qDvv8plQh6jetzM1gkhIltBFNQGzFUVuM=,tag:5Pai+HZTk2iRR0NMpIqa2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdVdkQjNmK0l0a3o1YW9l
            aUlzaWdkSlVCS3djUnFvUkU5K1hwNHVUVnhjCnRXVmlHbVlwYkd6Y3AzM3FQQmR3
            UlprQWpHWUtoN0QzbWFZUjBMeWRwLzQKLS0tIDk4ZXRLMUdxbkpMZ1FIclhjd1VJ
            SEFIeEE4a2haVlZHUGU0N05jVml1N00KwRB7D2gcXyYCL8oPRkxqfbbK1FA+ca5t
            KdzTRHsxiXwycGB+QSt65DHKwIJcEOVIEDQVWKibHzup6s94G0/MDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T22:09:15Z"
    mac: ENC[AES256_GCM,data:GG1J7zV+f5xw4wu6TTqVtlG39JuNBziRmW2a7xF0liI3tsr1pgKvFWReNhJr//kn/s2xNkOdHoyUoRh3ickNGiAj2mLGyZXlPTvjgQdDDY0p0RAo08iZbXz38T2uZghUST7vLTEAR2eJR5iFtIAwwaag8Z6tmqgdGouVRXWGh0Q=,iv:xI7A5FUMEwSSwvdBM11483iUJf2Uh2qnFfWLSm/Klp0=,tag:9tlvu25SE+q6En8U/d778A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
