apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:g8xLQu3H30uOSt7ALcel7q0JZCAU,iv:Wf8EDSFWqskNloAzzFxF0xs7zlOTfJEpBDmgbh6M5eg=,tag:+Bh/1HHloSkFXrBN1gB8hw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:oWbuI9ZDpiG/KwcpLV9hsZ0vrp6TV8LkWSTMwgTkEE+IvOYh,iv:cB4vxVfToTeTHS+3wA0IRixfJcgtCfp/OYnq5RjNC5I=,tag:3NBQib5UR/KUxJIVLHymjQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:0Pz0HCsngwvNGI86NQ==,iv:VYcNfEXindl/3xHSXZDx0aiWygio9zfasO0ega+kRAI=,tag:WApXZA4c3TY+EUGdWhhVgg==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:lcnvLPWE8JYdw0z95Zn2PcwN,iv:LFZNZP81kyvBDOYq1QS6XSWizAWMSwdTnNumLiybGTo=,tag:UFoJEczVMsaikRI7GW/BJw==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:2WfoWEetNPz1uYtpIus=,iv:npzeoTjrWS8UnTHm8m71PqYsibAGr1xYkQ3fKQVb7Eg=,tag:cQPsR42pXFog0da6fDvbRw==,type:str]
    SECRET_PAPERLESS_NGX_SECRET_KEY: ENC[AES256_GCM,data:IVZDeoHB09Lx+IiO0yU=,iv:p2jjI73kyybxSxxHJv1ebvPMJead4ulYFMJvKeGlSzQ=,tag:Z15MlOeDYXZfQyHBOWxd2A==,type:str]
    SECRET_SES_SMTP_HOST: ENC[AES256_GCM,data:eafi2pIDmAmAj/818ta+KfAUyB2GAZ6bTd8qW2AEL9zMIQ==,iv:uLdHqhZpcuhVVl3KezKoOqM3mU9PSiQFIQrSrBlpDkU=,tag:SI3+XtbtUNTo1UT8x6NSGA==,type:str]
    SECRET_SES_SMTP_PORT: ENC[AES256_GCM,data:7T52,iv:AksIEJdZ9SO1X3P/58ukrO2OyZMZ1C7rPbdlhRGDanE=,tag:dwx1llz7FVrK2KyjAPuDDg==,type:str]
    SECRET_SES_SMTP_FROM_EMAIL: ENC[AES256_GCM,data:fhxjPQ2kFH9r/aoVZzuhqfgLVmYN,iv:8pU8G7IifPr8XApwquvFqQUUbDdFpNW9mFT/v2xXNHE=,tag:jnVLbtJtV4qu00k/XS+7ag==,type:str]
    SECRET_SES_ACCESS_KEY: ENC[AES256_GCM,data:z826EhGYz7s3Z9Gjxzdu4wKmIj4=,iv:M/pq5kMoelgKSW7iFBoQtywddwcnvI08EvyJiDo1V3U=,tag:4UOPSuE58mFNl4v7b2jJbg==,type:str]
    SECRET_SES_SECRET_KEY: ENC[AES256_GCM,data:5vylVyht5Hk4t/8rhwaaAxjfyaLY4E3WIrKH8WHYnY05Zlqh1cfNqw==,iv:AEMxO6wurXKWTNuVmGs+Uu+mK3TFEJZYb392PRgJ65A=,tag:gKfPV+7YLbzV1H80gx+xZw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:FYk3t/Ugn8HpkG01JqKbJwlRpsssdEkEECpE68Z6f1TMYVsFfycCfQ==,iv:tkmV7kkuF6h2gb+00s0lqBoPzT6SOHGBQWDHsqzMmao=,tag:DgnfeXixsMo6auigFkUGow==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:006KAmNUkH8=,iv:Bm/kgrZp86ZEFkmgLHSAG5V8zBqxnG/VqD7X/AZRhPQ=,tag:iGpUp1gCdVSbxpAjqI26IA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:wcX1GeRmRWwjp0bJaishhBCEXQ==,iv:XoZ+Oel+L/HebNn1Vj3BgegrzalVwlKTnOUVQs81bew=,tag:Rgcnf8nfu2yyTIC68F3x5w==,type:str]
    SECRET_FRIGATE_CAMERA_AUTH: ENC[AES256_GCM,data:Pj/w8T0DjodPcSicEDqxJg==,iv:DS+qWF9+NY+HAQP+ya5qZGtzyORbPn8+8LVjUEfrAFU=,tag:aA16BBur/cTcpIl3e9wZOQ==,type:str]
    SECRET_VPN_USERNAME: ENC[AES256_GCM,data:FZ9pqn5ECN3O1wSsitrKFwTWz/4VJ562,iv:KAyMXHthDOejrlpS7Pbj+m7BlXCA31L1HNpKRVBBiSc=,tag:ZK4gQSZhsQ4rX9zwf1nlQg==,type:str]
    SECRET_VPN_PASSWORD: ENC[AES256_GCM,data:MOfpyUwakKVLPzxaJApJyQINQ3hzPZvv,iv:8ENPQyr7RH43azXLuu0xlNxala3iWcIuS3u213ejt8A=,tag:bOrfO8wf0pUjLBQZOsvbSw==,type:str]
    SECRET_SLACK_WEBHOOK_SERVICE_BOUNDCORP_OPS: ENC[AES256_GCM,data:zXaKdvZgfdhnzx8NVCgvhWmDPhgsF3aeifLRSJjiqjciXVSCjYcuvwGAQvUkHA==,iv:qLQ3yDAx13w/VAoR+9Tt3Gu8i36rAnxPVNHZbwc4nIE=,tag:0Vvp3DRK6WIBawt9U3McVw==,type:str]
    SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:w68qwalA+VHkOZTWVxaEVID39ds=,iv:jI0E3dNF9+WaWuQd1eLisDZ5kBbunOsErCbg09/u+xY=,tag:KfYzkmrR4RuJMucsKRCfUw==,type:str]
    SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AVGBD8nadPkv3pDcV2UiVJCmKBsvZ3O4yzorrEUIbB2HJOA+EYmcUQ==,iv:bKhPOIYJoO/em6J32XR4xW1xjxazDawxA7v68Skw254=,tag:4r12tRXLOt1K7nqqGMHmvg==,type:str]
    SECRET_VOLSYNC_REPOSITORY: ENC[AES256_GCM,data:u4xZq5wiB8FlLmQpcBWPmSi1bG53WA8nJMoy7QgJSzBXq6tr09TKWQWBqFLDKInOgSoBQOjbf9AYUs9o4Te3frTHlGdfJUTEPWcRkIeajFI=,iv:EwUbdhLC8N1AgO4RLZTHcDfqrOUXtTXiZ9qqMLPcSfY=,tag:rT9UaYZDBYay/rxZuKawTg==,type:str]
    SECRET_VOLSYNC_REPOSITORY_CTRL: ENC[AES256_GCM,data:yU4GpTY7QcVoip2viwP7RmaAnaFass2bNeuwRYh/wZ3jkUvTGv1m+xNRJNYHObsSZAq0cvgVFRMQAwfocZZdHOvZviDBCtPL7YoQu5Q=,iv:HgC54A4qQ/U9Uy3I3OX6pkY09VEZNGVHWYp0N3GZOKY=,tag:qf4+NZm6/FtXqj63tdxB6g==,type:str]
    SECRET_VOLSYNC_PASSWORD: ENC[AES256_GCM,data:fElmC2HGIXxO,iv:sIunLKYeKoStI9ZmCQRzdM6IFU7dUmOoEqurWdpB1Dg=,tag:1G9RclkfP0IYp+X476r9Yg==,type:str]
    SECRET_VOLSYNC_SCHEDULE: ENC[AES256_GCM,data:FBHR9URVBrN2,iv:jiw1mL3/dX1ZbDgPaInBdxHVDD5LW4E+uoGOyKuXbyE=,tag:AYAGTwe8fzJJ0RFeCO0VZw==,type:str]
    SECRET_TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:WS87EH9nWpSRfJnd8vO5tc9yRgiUtdlChrQS9k6MD6TOZkfH0NbCV28gCTNCZAVGczTZqrZEV65Q,iv:wC4HkJrjOHc0TPiaz5ZXnA/Ej3ChXvfBgInjBv26e1c=,tag:v1dwyAUtJgb6y/IrTDAaUQ==,type:str]
    SECRET_GETH_IP: ENC[AES256_GCM,data:qzmwCYQ5iBuHrPb29kQ=,iv:GohIqhqbM+Tq3x93bkuCKDdHz4SJydhnCcZIZixkKCE=,tag:7VHAMAxeIVWIqxY4iT2j8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TEFNL1VRMHVxK3dqb0Qr
            QldxNzFLc3Bpd05meEFraXdiUW0yYUErb0RZCndjWWppNHdGdWgxTndLVS9CSWU1
            VGsvblFxNkNRdnF5Sm9aZ21NZ0U4dE0KLS0tIElITE9GRnVKQkF1NlVGN1BORGxC
            c1pDbllyb1YyV3E1bGwyeDlQSEtweVkKNBVUgWHfwBWz5d2YMHwz7N5r4qjyVwZd
            AtMFDyaTtrjTZ9WteVV0kIIKU3LKPIsy41TIQkezlx4Fzdb0AxWotg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T23:29:09Z"
    mac: ENC[AES256_GCM,data:+Lh+zdFHKL+6MXbpBaOG1orNn3rDK6t3kMUZAD6TJYiB1dNapeaz5LNGEEVULTLj0chBPaLPlWMng0jhlIFGydQ+/EBLUB87JFxf1LGXxCIx60b6tvVuvjVU/CXkb5WCXb1icC3iCGwkp4gVOuzLn0O90iNg9lVZKpqMiDnwC4I=,iv:Gv5iei4y2uvw7aUhOyJANy6t8Wv2sF8r6n3WAbsgdkg=,tag:0pCJI49IhcKedTvQz73qag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
