apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vUwkuOiZ9S15Z1hNfgGzuV95Sqrb,iv:pdVt651MswclbMNuR3Dm5H70cVU1B9oLV1xRi9GSnDw=,tag:1oC0q7WsGFDKFshRz2kheA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:lLfKobAaRRMuABPd1RNg6lzMlpwC2jAZYEt3oSFszT4lORms,iv:7/xDxuNSzO0bd2mJJmnKrMv52LW5Vo4oAFNkPMZMYK0=,tag:tgpGh27EV3tcNZBjX56Ktw==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:ni6F1RoracWIyrvYqQ==,iv:Hh4QUsZJblrEFlIxqupNpRw6TFM5op9/gmZ3Wz5TEDw=,tag:tRd7R2nSHFCfSWOcFlF6XA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:w08+TyyTDU+VkUh60DX/Lu1C,iv:DJn/ElfRgFv/ruWA9nHWmFiH2vKs8Mv1a1RHnDw7KyQ=,tag:9kndJnlc/S1uqPFjYiCxDA==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:HyRV5911OuwDRgIIw08=,iv:+2J3lfTkrI8y2luPcaNe0XMW9Z09z5mcBqQZENceGM4=,tag:zJLNOv1yDHc28LOLTPZ3+g==,type:str]
    SECRET_PAPERLESS_NGX_SECRET_KEY: ENC[AES256_GCM,data:hfUTl13WkKjPBkvliUo=,iv:m5yXcMdZGGwgrY9zQc1w1gVdaZpdxIaYax57qyeJXgI=,tag:xD39jRAyPo8qKGyINir7iQ==,type:str]
    SECRET_SES_SMTP_HOST: ENC[AES256_GCM,data:4hV6cPhorBclzfYDcI1CwyOAXyjodC2pNdOZNk5LQSA4CQ==,iv:Jfmeo0hAlrl4TqQM7qbS8W/1VsGNaoV2efzGz4rjURY=,tag:1tBqI1sUuBGYJpwRdzZ0/A==,type:str]
    SECRET_SES_SMTP_PORT: ENC[AES256_GCM,data:zsKs,iv:7yCNi4rOSUv69BOjAfkH0zrDuiKpVgBBnPPMhDw1ySo=,tag:i7wsdboJHBAbUrySqduOAA==,type:str]
    SECRET_SES_SMTP_FROM_EMAIL: ENC[AES256_GCM,data:up/QBPVQmaLOFUOsY+VlY9ThIL/U,iv:h3Vv3KDPgwnIZ5ZHjEBld2tYjh7yxICCEjTgU10Tg44=,tag:qJMKmCP+06pJheikXtqP9w==,type:str]
    SECRET_SES_ACCESS_KEY: ENC[AES256_GCM,data:mjjw2PYkf0Mkt0+4/cZDrKShVsc=,iv:WqAJmgeqaTKi8iGmMoP8zWCeOUbf8U0zFSF8gDXq1Yc=,tag:Py27GB5Qko7Nq9oiu/t2NQ==,type:str]
    SECRET_SES_SECRET_KEY: ENC[AES256_GCM,data:46DYyl1x7TCD7ag8tZdWfLhYYzQbSbQ9M9pXyO0WYZbqIZrYUY7HCw==,iv:/oROfrMKiSNaVO10yeW0aZ+p9Sv6QeMMwFaD0+XxkWQ=,tag:yEs7oNuqhj4h2mFUhmOmGg==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:MiTXwr27jhBup2QockT3s3IxouL+AgWDcwqe9nJQDYfnob8zvYHIEQ==,iv:+ndripcB1vI5cvC/rReD8ZaIzKrwHQ28Xwak/xnaWnM=,tag:U5JiYoSsM51BMNKN7nqUtA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:bv7adELRa3M=,iv:gMUQ51TzZMoKErPaPSc4mVaGMjQhzhb5ys/v6fC0/Tw=,tag:8jmTDuwV8sepvEbB/3U+WQ==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:RijzgVR5ebFmzemBVhoa/3FO9A==,iv:uDNBjvI+z5U6KXSDnB5+MU8bKT1nz5ciDnSF89937G0=,tag:tPCuctsLQ/R10Dwqo+5z0w==,type:str]
    SECRET_FRIGATE_CAMERA_AUTH: ENC[AES256_GCM,data:WmzWcH9bOFus7NPOcUHFSA==,iv:bPRD7GdpPSNNe4UkOUqUuD4b2heU1oMzjmCwiMcP28A=,tag:SbgTD0hmPCsjnjktzyeI/Q==,type:str]
    SECRET_VPN_USERNAME: ENC[AES256_GCM,data:/ekggvFWFB/fWbFyU/U/K633fQmY1DeS,iv:/kEIqw6/gT9sGiAYIpJB1udYKQlthgE/+zeHFGaqfxc=,tag:tdvoG5VNYbXevkGfc4tVrQ==,type:str]
    SECRET_VPN_PASSWORD: ENC[AES256_GCM,data:t6KiIS9oau1BVD3Puef+PAAT/xAMwW/h,iv:K0DLPdlDVDhuprdIN2lFacj6hg9m3GNzjGzPIonPDxQ=,tag:U9GUNtl7eXBvCwEZWRfiRw==,type:str]
    SECRET_SLACK_WEBHOOK_SERVICE_BOUNDCORP_OPS: ENC[AES256_GCM,data:e7piHbsSjeRUZCfAxjs1A/8zoAoGzuSbsqnYj3Qmo3BR+FV3z3okRoE/o3BwZw==,iv:qGICo5VIt6h+wYKy4qMKyMWcnw08U8rekkdxI6fIzB0=,tag:OkMT2dkXPAvCK56d4Hsg3w==,type:str]
    SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:E7eFquEgs1t4vzKFG68BFAHXucU=,iv:2J66fA/m8TQvcZFyaSAq3KepUiuB8v+/+5VaG76j/iM=,tag:7eZtxIPdkhzp1FQs215kyg==,type:str]
    SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9FYWUzb7EMuFAKMfgKDLzu31MzOhvv8XVESBICGCy311gzkzfgnQAg==,iv:lVMRXJVAucx2mNQOEMuop/oZ43T/3wo+zgi4y+7EY+Q=,tag:rofWcDUqA1ISA38/yOLdew==,type:str]
    SECRET_VOLSYNC_REPOSITORY: ENC[AES256_GCM,data:2HRofIZKbnrE/4d75ACkJL1x257A+pFopUGwfvFuaiXuqacgZ0XB97+R43SkGH0ViF/YA93vWQmfOqI5AV44GM/9lWI5RlasXV3j8t6Rgb8=,iv:Tin7DtGVwXZPQr7r9uNDTlHNZ/uScJq6hz657kvkZb4=,tag:IhHu24pIB6oJpi5cE2ADeA==,type:str]
    SECRET_VOLSYNC_REPOSITORY_CTRL: ENC[AES256_GCM,data:5qW/HodvN9i9zyYXQqyOs0U2RYQES2jJUv7Cdd0Xvd0MQG0TRb/vh4MnCFjok5mi62gdGtxg0+qa0AYxkxo2OzoYt8L2zCsZJKiQDgo=,iv:nCEwwwoMXRPKqgqe+uOOkp6uDo3XPI0cynqFSpzIdmQ=,tag:aRY0Seqwhga4CE79Sgyejg==,type:str]
    SECRET_VOLSYNC_PASSWORD: ENC[AES256_GCM,data:RUJXXzH+qoLt,iv:8SonVjxwjEenLo3znFeZ6BQrQ6pEycORz9rfJXqdAJ0=,tag:0AKMI0O/ulmffBxrPKCM7A==,type:str]
    SECRET_VOLSYNC_SCHEDULE: ENC[AES256_GCM,data:v4OpLZX8CLsu,iv:W3ZSkFCOldFUJIYadICLLZXJeV6YF6semvc5WfSwsh8=,tag:jmm8e8+VEJ50+2FrCoN2Cw==,type:str]
    SECRET_TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:Fz858l9MPeqVBdM7olBHodPokE0A8tJ6FbTdB9th+e6vBt7oav4DVxSkpIWZ/k03h5E7WJ/RmhhK,iv:6eVvKRJviFxglCM3zZRKnq1olXDWPWz7yZenjWrpnmQ=,tag:n1Of/UgFm4yT1eZX5Ct9Qw==,type:str]
    SECRET_GETH_IP: ENC[AES256_GCM,data:BheMWtIilTGPn2kV0kc=,iv:ZP03S72X1aY40G7FlOQalDVazxUEI7cMu8/vO3Kq4BY=,tag:RuJVGEWHuAVNhgbS3mmxVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQWtkYjVobDQ4MWV6ZXhQ
            RkhFNGlJaEQyallPallySFpMUkRMWGY5WkM0CjQ0ZjRZY0QvRUFrbHd5VjB0ZHo1
            N0pHS0pqMExRWEZlaXE1SzU1WU1rZEEKLS0tIFpNMHUrdXJZNkxpcWVqN0FRV21O
            em8rT2ZuVlIxYnFBbUJjVEN5SUlWancK0pMOnDD5CM3fxyaJTLDg1lnIk7JUT6Gh
            yX59Fwkwalct5tFXQx+5CEfrUKpBUobSLzcpbw+A0jpAOQBV3IIt0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T18:58:03Z"
    mac: ENC[AES256_GCM,data:UYJ5a8E476vGovsygwz690EE7ALrLHcDlpqbfFL5oVivrOGyRMOGMx/ouoFxwdpnAUOZ8Gj/TYeSLKM3vfLT/zRJTF6H5Ur57NqGA9nXQKpG+hSFs4R0URsY1e1QJPxkrxpslDoYfzdmEvtcDaU/ce3GoFKpKizlGQwreiYSYZo=,iv:+7SAMS84SwKpq+JpLQz0uLHVbrpL2Pbu9ug6VXcbyiM=,tag:jUdYfcxxZjKJaT2yXVNbQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
