---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox-pod
  namespace: backups
spec:
  containers:
    - name: container
      image: ubuntu:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      env:
        - name: TZ
          value: "${TIMEZONE}"
      volumeMounts:
        - name: leeward-backups
          mountPath: /backups
        - name: syncthing-config
          mountPath: /config/syncthing
        - name: rclone-config
          subPath: rclone.conf
          mountPath: /root/.config/rclone/rclone.conf
          readOnly: true
  volumes:
    - name: leeward-backups
      persistentVolumeClaim:
        claimName: leeward-backups
    - name: rclone-config
      secret:
        secretName: rclone-config
    - name: syncthing-config
      persistentVolumeClaim:
        claimName: syncthing-config
