---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: docker.io/plexinc/pms-docker
      tag: public
    env:
      ADVERTISE_IP: "https://plex.${SECRET_PUBLIC_DOMAIN},http://${SVC_PLEX_ADDR}:32400"
      ALLOWED_NETWORKS: "10.1.1.0/24,10.1.2.0/24,10.42.0.0/16,10.43.0.0/16"
      TZ: "${TIMEZONE}"

    service:
      main:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_PLEX_ADDR}"
        ports:
          http:
            port: &port 32400
          # Plex DLNA Server
          # https://support.plex.tv/articles/200350536-dlna/
          dnla-tcp:
            enabled: true
            port: 32469
            protocol: TCP
          dnla-udp:
            enabled: true
            port: 1900
            protocol: UDP
          # GDM Network discovery
          # https://support.plex.tv/articles/200430283-network/
          gdm-1-udp:
            enabled: true
            port: 32410
            protocol: UDP
          gdm-2-udp:
            enabled: true
            port: 32412
            protocol: UDP
          gdm-3-udp:
            enabled: true
            port: 32413
            protocol: UDP
          gdm-4-udp:
            enabled: true
            port: 32414
            protocol: UDP
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /identity
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_PRIVATE_DOMAIN}"
        hosts:
          - host: &host "plex.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        existingClaim: mediamega-data
        mountPath: /data/library
        readOnly: false

      config:
        enabled: true
        mountPath: /config

      transcode:
        enabled: true
        type: emptyDir

    resources:
      requests:
        cpu: 500m
        memory: 2000Mi
        gpu.intel.com/i915: 1

      limits:
        memory: 5000Mi
        gpu.intel.com/i915: 1

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 50Gi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
