---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block-nvme-norepl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-hdd
  resources:
    requests:
      storage: 1Ti
