apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Q7ANjHkP63U3LLx4xm4vCyoYAL5qPAVlCoIKSYAfetyN7BkQ,iv:fAIa9q9K6HUlRPpWf3k5TEkXFjijJ8oWXTXH6Giz/8Q=,tag:JZ5s0gGQa3ucjOtnR8pQ+w==,type:str]
    credentials.json: ENC[AES256_GCM,data:YW8QBxEoceYzAdKM7OZdAWabqXRysPg28H+HWihcJgarMd+PnZJYHppmlTFb+ZzGf+3slrGLtyRelewkqD1m9mTeUTcW6sOYz/BthyKnQebRN+iW1yw99D6M2l5px77nYDhSKhWzKlAF1YAEcd9+Y4SyRZ3ZxZYhB25rrZWkgHj6aVd7G35t4nBYYwt3/wz30fpRNvBLnOR6Hvwz0Uuk6Dkef6UOgXKqwdBNS/fP0w==,iv:O73SFZRB1jv7ni15NFGN2OREKGTNLZwnz0YOzTCmres=,tag:ZZQQM8EAx4TMI9RtaPpUTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L1RGL21HRE9KQjFEcTFK
            YjBBbGhGdC80dVY0SDlDRW1zVTM4aHpPQmxBCnY0U3lsWlNnNUVVYTNacW0ra2d3
            ZUZOQU9BWmE1M0I0V09oQ3c5SWZkZUkKLS0tIGdDa3dvdUVDM053dEFEMkZqS3Jx
            Q1ZYKzdIVXhNZ1hURUxaV0FreFBlcEkK4KGy4ox8AEEbZDxXPuMdt2pY5xNj24IS
            Xflzmadg7mHlOF2KL5x3XC4SllOXqkwR76PbSKInPsnAwsWqFegQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T02:00:33Z"
    mac: ENC[AES256_GCM,data:fsr0Wr1JdYrnWE/4fP8RRGNbM/btHqQcSeE1JBxTzoLcm+qyOG9JmMamlQIB9PL5zTyxMQE6zAaNtRoTKQmZ1wJ8sBR+y6HFpql5YQA/AmrSU7XpI9rcsKAgAI7lF0QvzJiln0NY1MXuqBHZovk0HUynlM3Swalfe+sopKq2458=,iv:cLJM6/mzaFzDHGtxqTfBxfWTFpK0Wa6TvpLwmP28QZQ=,tag:RuoZ7bW0Yzt+tP77XJw3KA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
