apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:cQFafVKvDQ8gODYG8Okw6WSHqxCj55eTZbgnT4izu30nr3F9,iv:jRzZZquoYAVm3I1+BXo6EG3iyvQgHqQng/ozHD945fg=,tag:wXzbos7lsf1Zk2RhERSTuA==,type:str]
    credentials.json: ENC[AES256_GCM,data:AG5gYwMPjH2g9SAK5WcWc8Eu8mJRySS4ms1EjbGpHGkumdTclYFNe/OOu1GHWmy36WuFqj7CUyZhrTJ1dmfQedQGntAYgELbO2aLu7McPHXcP/GVV7xo1gBbiV7CG1gQL9rifkK+HFzylXg8BRVbpHUZSf3HbjObs4e2WmwzgZJQRVNoi1OwNAQ9p6bq37gMaAhMIHtqtbaKQj4D3l071x3Vus8OjERyFK7lDdsEUQ==,iv:Aiil1Hu+WwU5RBZuL30pIIszOaaKewKYxTtAkYrlK3w=,tag:N5mwnB5KbQ50M4hmA2pd0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOFpTZ0N2UDVrYkZXZlZl
            bEhKLzJVMG1FZ012TzloY1R4QmtDdjh1dW1jCm9sZ3NPWG9hNG8yeUZSMmEvUFQv
            Sm1IK2YycUdWN1ZzYVRLTGhpVEJMSm8KLS0tIE9RTnhrUTFGcDRweUZNS3B3RVk5
            WldwZ2NtSnF1djhTVmgvT3doNXAxcG8KyB+e5MWqBexKwcgDmjGO2txrLJbgYUt7
            vKOmMebEPj4J0J3x5TWjccEXPyWmpKwzBH+2Awj2D5IkJBBxdlzmhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T21:32:57Z"
    mac: ENC[AES256_GCM,data:irZCUvhTewWO+E3JkBxpuHfDhNA/96ZgfKH9qjjYg+oa+DG6CC1Gjgm/yaCoKfkIICOg56oIxerktcxEVf3c6DETjNhEOrcC7lzQbiXr2vplztmZXEEXT+0YDkd85zx1G6h0+o3Il4xirxn6hxasTF+KywZ9FMLpNENP5eZ1WfU=,iv:NC0qJ+GpYbVn4wZeDAjJ00YWWKAIeU+TWmJ3lk92hjY=,tag:jGdxQgi7f/OBZyEYJMGBIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
