---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crunchydata-pgo
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: pgo
      version: 5.6.1
      sourceRef:
        kind: HelmRepository
        name: crunchydata
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
