# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.22.0/_definitions.json#/definitions/io.k8s.api.core.v1.Secret
apiVersion: v1
kind: Secret
metadata:
    name: crunchy-postgres-secret
    namespace: database
stringData:
    s3.conf: ENC[AES256_GCM,data:VqyF8ojioi/etz0dN+zjwYOV1b3AxPhDE1XK1uC6JedM0sg1sB9TPjwvWEQreJ9Cfs4WwGglOec7l6+gxK7YercFXSIiMSN+WjBLkUfppOj98C0fIo0K0/Btkic7/Eu9CieFRpHmj5prTl42bjoeh54Mrtt3XC5I/kLIb5GS69c676QmMZrsMHhkwK5yYsS6XNmicNIVfR+goxcB1fBImzHoa7PPMvonpAL8alQ8L6iU3m896CaLaCZQdJdiscL3tmVuRpIvywfCeULU,iv:6WHG1ff9/7dqYFfYuP9djq7A/jHnSzABqxVyFQbDcvQ=,tag:/1v+jELMOyzqvMGrota4ow==,type:str]
    encryption.conf: ENC[AES256_GCM,data:TZbE2xAcEuNxTEHEidYb8Aa8MBNymOHosXwP6EAvw8nGMwB8HbLzUq+g8YAKzGfgj4IXQ4ZCJaUCGKo4znXOjHQ=,iv:nwIhIRTojcZT4RPm8r4HstxZFeIai8IX2ykpoXeSsRc=,tag:OVumrMcJz/9/LYmXLJCHJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYm8wYmgzUDlTbmhPMVNl
            ak9wRmVHYzBURCtRYk0xei9pYlgveXNqeG1FCmt5dzZSOSs2SVpoc2ZJc1RNVFk3
            UHc3YXNmc2EyU3VESnVXc2IxNVEwS3cKLS0tIFZXRWd2R3pTT1hMcHY0a3VnYUdH
            OXZIa3dpdU5oQjNJb244TEJsbHB4UjgKMOKIHi7C5nGWweKm0ngUP1CLtPPXVr4J
            2S4Xkdwhi0bvjrA/o1ku7Qius+mMFhvq/jlzJ2tNymN5F08PiWSrCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T01:03:22Z"
    mac: ENC[AES256_GCM,data:bIkXzZFa19b9mvV7uYeiRZZAM4sfWmuS9YeNCFxfKGWzvFD9bKzXg+xCZxwdM6jiHzTAo80V32OWx7gL4GqIYF/6wM4703bbPld9+kfC9t8SbKfJ1rymowyy3CbMceOgDeYFMIGDGmEaVP9PJHdEcd03w368GgZVEOuSypUhmSc=,iv:4EeZd/G5sHVcib6z9ziGLW5wlbOHlPIOLOmBMAfkwvI=,tag:zTEiFF2Z9aQGSQll33DYHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
