apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Add any other custom values here
    # For default values, refer to:
    # https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/charts/v4.9.0/csi-driver-nfs/values.yaml
