---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-nova-nvm
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-test-claim
  containers:
    - name: fio
      image: nixery.dev/shell/fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: nfs-volume
